# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

name:                           Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name:                       Coverage
    runs-on:                    ubuntu-latest

    steps:
      - uses:                   actions/checkout@v3
      - uses:                   actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: rustup component add llvm-tools-preview

      # TODO(#315) Re-include caching that also includes the Rust version in the cache key

      ## Coverage steps

      - name:                   Install grcov
        uses:                   actions-rs/install@v0.1.2
        with:
          crate: grcov
          version: latest
          use-tool-cache: true
      - name:                   build
        env:
          RUSTFLAGS: -Cinstrument-coverage
        run:                    cargo build --verbose
      - name:                   test
        env:
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: gluesql-%p-%m.profraw
        run:                    cargo test --all-features --verbose

      - name: Run grcov
        run: |
          mkdir coverage
          grcov . \
            --binary-path ./target/debug/ \
            -s . \
            -t lcov \
            --branch \
            --ignore-not-existing \
            --ignore "/*" \
            --ignore "examples/*.rs" \
            --ignore "cli/src/{cli,helper,lib,main}.rs" \
            --excl-line "#\\[derive\\(" \
            -o ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
